/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntrack_audioroute_Audioroute_Audioroute */

#ifndef _Included_com_ntrack_audioroute_Audioroute_Audioroute
#define _Included_com_ntrack_audioroute_Audioroute_Audioroute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    createInstance
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_ntrack_audioroute_Audioroute_createInstance
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    sendSharedMemoryFileDescriptor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_doSendSharedMemoryFileDescriptor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    createModule
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_createModule
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    deleteModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_deleteModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    connectPorts
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_connectPorts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    disconnectPorts
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_disconnectPorts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    activateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_activateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    deactivateModule
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_deactivateModule
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ntrack_audioroute_Audioroute_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    isActive
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ntrack_audioroute_Audioroute_isActive
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    isRunning
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ntrack_audioroute_Audioroute_isRunning
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    isConnected
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ntrack_audioroute_Audioroute_isConnected
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    getInputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_getInputChannels
  (JNIEnv *, jobject, jlong, jint);

JNIEXPORT jintArray JNICALL Java_com_ntrack_audioroute_Audioroute_getConnectedBuses
        (JNIEnv *, jobject, jlong, jint, jboolean isInput);
/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    getOutputChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_getOutputChannels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ntrack_audioroute_Audioroute_Audioroute
 * Method:    getProtocolVersion
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_getProtocolVersion
  (JNIEnv *, jobject, jlong);

JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_Audioroute_getEngineData
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
