/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ntrack_audioroute_audioroute_internal_SharedMemoryUtils */

#ifndef _Included_com_ntrack_audioroute_audioroute_internal_SharedMemoryUtils
#define _Included_com_ntrack_audioroute_audioroute_internal_SharedMemoryUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntrack_audioroute_audioroute_internal_SharedMemoryUtils
 * Method:    receiveSharedMemoryFileDescriptor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_internal_SharedMemoryUtils_receiveSharedMemoryFileDescriptor
  (JNIEnv *, jclass);

/*
 * Class:     com_ntrack_audioroute_audioroute_internal_SharedMemoryUtils
 * Method:    closeSharedMemoryFileDescriptor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ntrack_audioroute_internal_SharedMemoryUtils_closeSharedMemoryFileDescriptor
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
